---
# Playbook to deploy Ghost and its components

- name: DB install and start
  hosts: localhost 
  roles:
      - mysql
  tags: 
    - dbinstall

- name: Ghost install and start
  hosts: localhost
  roles:
      - ghost
  tags:
    - ghostinstall

- name: DataBase Update
  hosts: localhost
  roles:
      - bd_update
  tags:
    - bd_update
      