---
# Playbook to deploy Ghost and its components

- name: DB install and start
  hosts: localhost 
  roles:
      - mysql
  tags: 
    - dbinstall

- name: Ghost install and start
  vars_files:
    - secrets.yml
  hosts: localhost
  roles:
      - ghost
  tags:
    - ghostinstall