# Installing the Monitoring and Logging agents
- hosts: localhost
  roles:
    - monitoring
    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: monitoring

    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: logging