---
# Playbook to test the full deployment of Ghost (from creation to destruction)

- import_playbook: deploy-ghost.yml

- name: Tests
  hosts: localhost
  gather_facts: true
  vars_files:
    - secrets.yml
  roles:
    - { role: test_ghost }

- import_playbook: undeploy-ghost.yml

- import_playbook: deploy-ghost.yml

- name: Tests
  hosts: localhost
  gather_facts: yes
  vars_files:
    - secrets.yml
  roles:
    - { role: test_ghost }

- import_playbook: undeploy-ghost.yml delete_data='true'

- import_playbook: deploy-ghost.yml

- name: Tests
  hosts: localhost
  gather_facts: true
  vars_files:
    - secrets.yml
  roles:
    - { role: test_ghost }