---
# Make a post
# Create a session, and store the cookie in ghost-cookie.txt
- name: Create a session
  shell: 'curl -c ghost-cookie.txt -d username=ascn@example.com -d password={{ ghost_pass }} -H "Origin: http://{{ ghost_ip }}" -H "Accept-Version: v3.0" http://{{ ghost_ip }}/ghost/api/admin/session/'

- name: Create header
  set_fact:
    header: "-H 'Content-Type: application/json' -H 'Accept-Version: v3.0' -H 'Origin: http://{{ ghost_ip }}'"

# Use the session cookie to create a post
- name: Create a Post 
  shell: "curl -b ghost-cookie.txt -d '{\"posts\": [{\"title\": \"Hello World\",\"status\": \"published\"}]}' {{ header }}  http://{{ ghost_ip }}/ghost/api/admin/posts/"


- name: Get Permissions
  shell: "curl -b ghost-cookie.txt {{ header }} http://{{ ghost_ip }}/ghost/api/admin/roles/?permissions=assign > roles.json" 

- name: Get Json Var
  set_fact:
    ids: "{{ lookup('file', 'roles.json') | from_json }}"


- name: Create a new Invite For Different Roles
  shell: "curl -b ghost-cookie.txt -d '{\"invites\":[{\"token\":null,\"email\":\"{{ item[0] }}@exemplo.pt\",\"expires\":null,\"status\":null,\"role_id\":\"{{ item[1]  }}\"}]}' {{ header }} http://{{ ghost_ip }}/ghost/api/admin/invites/"
  loop:
    - [admin, "{{ ids.roles[0].id }}"]
    - [editor,"{{ ids.roles[1].id }}"]
    - [author,"{{ ids.roles[2].id }}"]
    - [contrib,"{{ ids.roles[3].id }}"]

- name: Create Accounts
  shell: | 
      export MAILTRAP_KEY={{ mailtrap_key }}
      export GHOST_IP={{ ghost_ip }}
      envsubst < roles/test_post/templates/test.py | python3 
      unset MAILTRAP_KEY
      unset GHOST_IP
  register: result

-    debug:
       msg: "{{ result.stdout.split('|') }}"