---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        ports:
        - containerPort: 2368
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__database
          value: ghost
        - name: database__connection__user
          value: teste
        - name: database__connection__password
          value: "$PASS"
        - name: url
          value: 'http://35.246.39.57:80/'
        - name: mail__options__auth__user
          value: "ad7e50d8973faf"
        - name: mail__options__auth__pass
          value: "7a9b4a2b741388"
        - name: mail__transport
          value: "SMTP"
        - name: mail__options__port
          value: "2525"
        - name: mail__options__service
          value: "Mailtrap"
        - name: mail__options__host
          value: "smtp.mailtrap.io"
        - name: mail__from
          value: "GRUPO_35 <ascn.35@gmail.com>"
#        - name: mail__options__ignoreTLS
#          value: "false"


        
