---
- name: Delete Pods
  shell: kubectl delete pod --all

- name: Delete Deployments
  shell: kubectl delete deployment.apps --all

- name: Delete Services
  shell: kubectl delete service --all

- name: Delete Dashboard
  shell: gcloud monitoring dashboards delete 'ghost_monitoring' --quiet

- name: Delete HPA
  shell: kubectl delete hpa --all